# Generated by Django 4.0.4 on 2022-05-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('info', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
