# Generated by Django 4.0.4 on 2022-05-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='info',
            new_name='address_info',
        ),
    ]
